name: GitHub Actions Demo
on:
  push: 
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "Here my event name ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List of files
        run: |
          echo "Repository ${{ github.repository }} has the  files:"
          tree
      
      
        
      
        
        
  
  
  
